name: Docker Image CI

on:
  push:
    branches:
    - feature/*
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt

    - name: Push Image
      run: |
        cd ./python
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" > ~/docker-login.txt
        cat ~/docker-login.txt | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
        #echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "DOCKERHUB_USERNAME" --password-stdin
        docker build . --file Dockerfile --tag DOCKERHUB_USERNAME/python-app:$(date +%s)
        docker push DOCKERHUB_USERNAME/python-app:$(date +%s)
