name: Docker Image CI

on:
  push:
    branches:
    - feature/*
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./python/Dockerfile --tag guilhermerodriguesti/python-app:$(date +%s)
    - name: Push Image
      run: |
        echo "${{ secrets.DOCKER_HUB_LOGIN }}" | docker login -u "guilhermerodriguesti" --password-stdin
        docker push guilhermerodriguesti/python-app:$(date +%s)
